### ISSUE TITLE
Feature Request(s)

### ISSUE THREAD

**Issue by Zyrusse** [Kalaborative/BombPartyHelper#1]
Hello, I love this helper you made, very useful when studying prompts.

So you know the "search_en.py" and "search_fr.py," is there a way to make it automatic? Like for it to get what prompt is on the current game? _(and then show the 20 possible solutions)_

I don't know if you know this but it'd be nice if it would work on the new site, [jklm.fun](jklm.fun). Hope you consider this, if possible. Thanks!

**Comment by Kalaborative** [comment]
Hi, thanks so much!

I could try playing around with the `requests` module to see if I can grab the letters that way, but I doubt it.

I do however have an idea how to automatically get it with Selenium, so I could implement that in `bot.py`

I will also look into making one for jklm.fun :smile:

**Comment by Zyrusse** [comment]
Thank you so much for considering my suggestion! I asked for this so I can see possible solutions to whatever prompt each player receives. (while spectating, it'd be cheating if it was in-game.)

_(also the sowpods.txt I used is derived from the actual dictionary the game uses, unfortunately the one on jklm.fun is slightly different according to gameplay)_

**Comment by Zyrusse** [comment]
Is there a way for "search_en" and "search_fr" to have a function so that you can specify what letter(s) should be included in the word? For example:

`Enter your string: itt`

It would give words like bitter, litter, ditto, etc.

`Enter your string: itt j`

It would give words with itt **_BUT_** _there needs to be a **j** in the word_.
Like jitter, jitterbugging, etc.

Maybe for multiple letters too?

`Enter your string: itt jb`

It would give words with itt **_BUT_** _there needs to be a **j** and a **b** in the word_.

Like jitterbugging, etc.

**Comment by Kalaborative** [comment]
I thought about that actually. Let me see what i can do!

**Comment by Kalaborative** [comment]
@Zyrusse got it to work!
