### ISSUE TITLE
auto_bot.py

### ISSUE THREAD

**Issue by Zyrusse** [Kalaborative/BombPartyHelper#3]
The ENGLISH option in auto_bot.py has this "Press enter to confirm" function while the FRENCH one doesn't.

**Comment by Kalaborative** [comment]
Strange ... It looks like they're commented out for both languages...

**Comment by Kalaborative** [comment]
https://github.com/Kalaborative/BombPartyHelper/blob/6e1fe30cc48dac7955ba11eade9aed902110469b/auto_bot.py#L124

**Comment by Kalaborative** [comment]
Are you sure you're referencing `auto_bot.py` or possibly the other two scripts `manual_bot.py` or `minibot.py`?

**Comment by Kalaborative** [comment]
Oh I just realized your fork is 6 commits behind. Update your repo and you should be good.

Run `git pull origin master` in your local Git directory

**Comment by Kalaborative** [comment]
New update, please run a git pull or re-fork it to apply the updates locally
